/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.kafka.image;

import org.apache.kafka.image.writer.ImageWriter;
import org.apache.kafka.metadata.PartitionRetirementAuthorityState;
import org.apache.kafka.metadata.PartitionRetirementAuthorityState.Key;
import org.apache.kafka.metadata.PartitionRetirementAuthorityState.Value;

import java.util.Comparator;
import java.util.Map;
import java.util.Objects;

/**
 * Full-state, immutable view of replayed KRaft retirement authority records.
 *
 * <p>Records are never generated by production controller operations in this
 * version. A nonempty image could only originate from an externally injected
 * record or a future gated controller implementation. No decoded image is an
 * authorization to delete data.</p>
 */
public record PartitionRetirementAuthorityImage(Map<Key, Value> entries) {
    public static final PartitionRetirementAuthorityImage EMPTY =
        new PartitionRetirementAuthorityImage(Map.of());

    public PartitionRetirementAuthorityImage {
        entries = Map.copyOf(Objects.requireNonNull(entries, "entries"));
    }

    public boolean isEmpty() {
        return entries.isEmpty();
    }

    public Value get(Key key) {
        return entries.get(key);
    }

    /** Retains terminal topic-ID tombstones; snapshot compaction must never discard them. */
    public void write(ImageWriter writer) {
        entries.entrySet().stream()
            .sorted(Comparator
                .comparing((Map.Entry<Key, Value> e) -> e.getKey().topicId().toString())
                .thenComparingInt(e -> e.getKey().partitionId()))
            .forEach(e -> writer.write(0, PartitionRetirementAuthorityState.record(e.getKey(), e.getValue())));
    }
}
